// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfoV-aguw1xumfPHRAvI3EirCFeclNEk4',
    appId: '1:1086411140853:web:2a62d8461fc55bbf1edfbc',
    messagingSenderId: '1086411140853',
    projectId: 'todo-47286',
    authDomain: 'todo-47286.firebaseapp.com',
    storageBucket: 'todo-47286.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFLpRwWebvgBabPoT_aQfMNfM3Re2aBeM',
    appId: '1:1086411140853:android:ad5b72f518bdea761edfbc',
    messagingSenderId: '1086411140853',
    projectId: 'todo-47286',
    storageBucket: 'todo-47286.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD30sps3j3zN68M3hL_8EqZ9XD8YKMSHA',
    appId: '1:1086411140853:ios:bccd53b7751f70db1edfbc',
    messagingSenderId: '1086411140853',
    projectId: 'todo-47286',
    storageBucket: 'todo-47286.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD30sps3j3zN68M3hL_8EqZ9XD8YKMSHA',
    appId: '1:1086411140853:ios:bccd53b7751f70db1edfbc',
    messagingSenderId: '1086411140853',
    projectId: 'todo-47286',
    storageBucket: 'todo-47286.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfoV-aguw1xumfPHRAvI3EirCFeclNEk4',
    appId: '1:1086411140853:web:d643bc2fa755677c1edfbc',
    messagingSenderId: '1086411140853',
    projectId: 'todo-47286',
    authDomain: 'todo-47286.firebaseapp.com',
    storageBucket: 'todo-47286.appspot.com',
  );
}
